### ISSUE TITLE
Pascal architecture support -CUDA 8.0 support

### ISSUE THREAD

**Issue by shridharkini6** [pfnet/chainer#1887]
Does it support Pascal Architecture with CUDA 8.0

**Comment by unnonouno** [comment]
Yes. From v1.18.0, we supports CUDA 8.0. And I'm using GTX 1080 and CUDA 8.0.

**Comment by shridharkini6** [comment]
getting this error
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version
can you mention driver version?

Card : GTX 1080
CUDA 8.0
cudann v5.1
Driver Version: 367.27

**Comment by unnonouno** [comment]
I'm using CUDA 8.0.44 downloaded from the official site https://developer.nvidia.com/cuda-downloads
And  I'm using CUDA driver 367.57, which the official package contains .

**Comment by manuelschmidt** [comment]
I am personally using the following configuration:
- GTX 1060 6GB
- CUDA 8.0.44
- Driver 370.28
- cudnn v5.1
- Ubuntu 14.04

Today I also faced some problems with Chainer v.1.18.0 regarding CUDA.
So I removed the NVIDIA Driver and CUDA completely using:
sudo apt-get remove --purge nvidia-*
sudo apt-get install ubuntu-desktop
sudo rm /etc/X11/xorg.conf
echo 'nouveau' | sudo tee -a /etc/modules

Then I removed CUDA with:
cd /usr/local/cuda-8.0/bin
sudo perl uninstall_cuda_8.0.pl (need to apt-get perl before in case you don't have it installed)

When reinstalling I followed this guide:
https://alliseesolutions.wordpress.com/2016/09/08/install-gpu-tensorflow-from-sources-w-ubuntu-16-04-and-cuda-8-0-rc/
But with the difference that I first installed CUDA and cudnn as described there and after that installed the newest 370.28. If you then set all the path variables correctly like stated in that instruction and install also chainer from scratch following the installation instruction everything should work fine and is up-to-date then ;)

Hope it helps

**Comment by shridharkini6** [comment]
I installed 367.57 divers. Now it works. 
Thanks manuelschmidt and unnonouno
