### ISSUE TITLE
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory ?

### ISSUE THREAD

**Issue by mjiansun** [pfnet/chainer#2373]
ubuntu14.04
**In .bashrc,** 
export PATH=/usr/local/cuda/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/usr/local/cuda/lib64:$LIBRARY_PATH
python2.7
sudo pip install chainer (version 1.21.0)
cupy 1.0.0a1

**when i run at terminal 's@s-pc:~/myproject/brain_segmentation-master$ python train.py'**
Traceback (most recent call last):
  File "train.py", line 91, in <module>
    main()
  File "train.py", line 73, in main
    outputs = vrn(x_train, train=True)
  File "/home/s/myproject/brain_segmentation-master/model.py", line 96, in __call__
    c3 = F.clipped_relu(self.c3deconv(h))
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/connection/deconvolution_nd.py", line 69, in __call__
    outsize=self.outsize, use_cudnn=self.use_cudnn)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/deconvolution_nd.py", line 360, in deconvolution_nd
    return func(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/deconvolution_nd.py", line 182, in forward
    return self._forward_cudnn(x, W, b)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/connection/deconvolution_nd.py", line 118, in _forward_cudnn
    y = cuda.cupy.empty(y_shape, dtype=x.dtype)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/basic.py", line 19, in empty
    return cupy.ndarray(shape, dtype=dtype, order=order)
  File "cupy/core/core.pyx", line 88, in cupy.core.core.ndarray.__init__ (cupy/core/core.cpp:6333)
  File "cupy/cuda/memory.pyx", line 280, in cupy.cuda.memory.alloc (cupy/cuda/memory.cpp:5988)
  File "cupy/cuda/memory.pyx", line 431, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:9256)
  File "cupy/cuda/memory.pyx", line 447, in cupy.cuda.memory.MemoryPool.malloc (cupy/cuda/memory.cpp:9162)
  File "cupy/cuda/memory.pyx", line 342, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:7817)
  File "cupy/cuda/memory.pyx", line 368, in cupy.cuda.memory.SingleDeviceMemoryPool.malloc (cupy/cuda/memory.cpp:7592)
  File "cupy/cuda/memory.pyx", line 260, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5930)
  File "cupy/cuda/memory.pyx", line 261, in cupy.cuda.memory._malloc (cupy/cuda/memory.cpp:5851)
  File "cupy/cuda/memory.pyx", line 35, in cupy.cuda.memory.Memory.__init__ (cupy/cuda/memory.cpp:1772)
  File "cupy/cuda/runtime.pyx", line 207, in cupy.cuda.runtime.malloc (cupy/cuda/runtime.cpp:3429)
  File "cupy/cuda/runtime.pyx", line 130, in cupy.cuda.runtime.check_status (cupy/cuda/runtime.cpp:2241)
cupy.cuda.runtime.CUDARuntimeError: cudaErrorMemoryAllocation: out of memory

**when i use pycharm to run my code, it happens the problem.**
Traceback (most recent call last):
  File "/home/s/myproject/brain_segmentation-master/train.py", line 91, in <module>
    main()
  File "/home/s/myproject/brain_segmentation-master/train.py", line 73, in main
    outputs = vrn(x_train, train=True)
  File "/home/s/myproject/brain_segmentation-master/model.py", line 80, in __call__
    h = F.relu(self.bnorm1a(h, test=not train))
  File "/usr/local/lib/python2.7/dist-packages/chainer/links/normalization/batch_normalization.py", line 130, in __call__
    ret = func(x, gamma, beta)
  File "/usr/local/lib/python2.7/dist-packages/chainer/function.py", line 199, in __call__
    outputs = self.forward(in_data)
  File "/usr/local/lib/python2.7/dist-packages/chainer/functions/normalization/batch_normalization.py", line 161, in forward
    mean = x.mean(axis=axis)
  File "cupy/core/core.pyx", line 810, in cupy.core.core.ndarray.mean (cupy/core/core.cpp:17851)
  File "cupy/core/core.pyx", line 818, in cupy.core.core.ndarray.mean (cupy/core/core.cpp:17722)
  File "cupy/core/reduction.pxi", line 254, in cupy.core.core.simple_reduction_function.__call__ (cupy/core/core.cpp:51824)
  File "cupy/util.pyx", line 37, in cupy.util.memoize.decorator.ret (cupy/util.cpp:1458)
  File "cupy/core/reduction.pxi", line 181, in cupy.core.core._get_simple_reduction_function (cupy/core/core.cpp:50325)
  File "cupy/core/reduction.pxi", line 108, in cupy.core.core._get_simple_reduction_kernel (cupy/core/core.cpp:48118)
  File "cupy/core/carray.pxi", line 87, in cupy.core.core.compile_with_cache (cupy/core/core.cpp:33111)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 125, in compile_with_cache
    env = (arch, options, _get_nvcc_version())
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 22, in _get_nvcc_version
    _nvcc_version = _run_nvcc(cmd, '.')
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 61, in _run_nvcc
    raise OSError(msg)
OSError: Failed to run `nvcc` command. Check PATH environment variable: [Errno 2] No such file or directory

**Comment by mjiansun** [comment]
mjiansun shi zz

**Comment by unnonouno** [comment]
In the former case, as an error says your environment does not have enough memory. Please reduce  batch size.

In the later case, it looks `nvcc` is not found in your `PATH` environment variable. Please check configuration of pycharm.

**Comment by mjiansun** [comment]
@unnonouno Thank you very much.The above problem is solved.
But the following problem comes up.
Using gpu device 0: GeForce GTX 960 (CNMeM is disabled, cuDNN 5005)
GPU: -1
unit: 1000
Minibatch-size: 10
epoch: 20

Traceback (most recent call last):
  File "chainer-master/examples/mnist/train_mnist.py", line 126, in <module>
    main()
  File "chainer-master/examples/mnist/train_mnist.py", line 96, in main
    if chainer.training.extensions.PlotReport.available():
AttributeError: type object 'PlotReport' has no attribute 'available'

I have done the following operation.
`sudo pip uninstall chainer`
`sudo CUDA_PATH=/usr/local/cuda pip install chainer`

**Comment by unnonouno** [comment]
`PlotReport.available` is newest feature and is not supported in the latest stable release v1.21.0. Please use `v1.21.0` tag or use `https://github.com/pfnet/chainer/archive/v1.21.0.tar.gz`

**Comment by mjiansun** [comment]
At Mnist,
I found this problem was caused by 'extensions.PlotReport.available()'.When i commented this code, i can run successfully.

`    # Save two plot images to the result dir
    # if extensions.PlotReport.available():
    #     trainer.extend(
    #         extensions.PlotReport(['main/loss', 'validation/main/loss'],
    #                               'epoch', file_name='loss.png'))
    #     trainer.extend(
    #         extensions.PlotReport(
    #             ['main/accuracy', 'validation/main/accuracy'],
    #             'epoch', file_name='accuracy.png'))`
